### ISSUE TITLE
启用插件  Oops! Something went wrong. Please reload the page and try again

### ISSUE THREAD

**Issue by dbarobin** [jjandxa/flarum-ext-chinese-search#2]
后台点击启用插件，提示 Oops! Something went wrong. Please reload the page and try again
版本：v0.1.0-beta.7
PHP 版本：5.6.32
MySQL：5.7.20

**Comment by dbarobin** [comment]
POST https://bcage.one/api/extensions/jjandxa-chinese-search

null

**Comment by dbarobin** [comment]
2018/01/06 16:57:37 [error] 18691#18691: *1075 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /xxx/xxx/vendor/jjandxa/flarum-ext-chinese-search/src/Utils/XunSearchUtils.php on line 17" while reading response header from upstream, client: 172.68.253.87, server: xxx.xxx, request: "POST /api/extensions/jjandxa-chinese-search HTTP/1.1", upstream: "fastcgi://127.0.0.1:xxxx", host: "xxx.xxx", referrer: "https://xxx.xxx/admin"

**Comment by jjandxa** [comment]
@dbarobin 请发一下 flarum 下的 config.php 文件

**Comment by dbarobin** [comment]
@jjandxa 一致哈
