### ISSUE TITLE
flarum beta8 启用插件出错

### ISSUE THREAD

**Issue by oyjcmyn** [jjandxa/flarum-ext-chinese-search#5]
flarum beta8 启用插件出错
`./vendor/bin/xs search -p ./vendor/jjandxa/flarum-ext-chinese-search/app.ini`
这样测试没有问题

`TypeError: Argument 1 passed to Illuminate\Filesystem\Filesystem::{closure}() must be an instance of Plugin\XunSearch\Utils\XunSearchUtils, instance of Illuminate\Database\Schema\MySqlBuilder given in /web/discuss/vendor/jjandxa/flarum-ext-chinese-search/migrations/2017_10_15_080540_init.php:10↵Stack trace:↵#0 [internal function]: Illuminate\Filesystem\Filesystem->{closure}(Object(Illuminate\Database\Schema\MySqlBuilder))↵#1 /web/discuss/vendor/flarum/core/src/Database/Migrator.php(197): call_user_func(Object(Closure), Object(Illuminate\Database\Schema\MySqlBuilder))↵#2 /web/discuss/vendor/flarum/core/src/Database/Migrator.php(130): Flarum\Database\Migrator->runClosureMigration(Array)↵#3 /web/discuss/vendor/flarum/core/src/Database/Migrator.php(113): Flarum\Database\Migrator->runUp('/web/discuss/pu...', '2017_10_15_0805...', Object(Flarum\Extension\Extension))↵#4 /web/discuss/vendor/flarum/core/src/Database/Migrator.php(87): Flarum\Database\Migrator->runMigrationList('/web/discuss/pu...', Array, Object(Flarum\Extension\Extension))↵#5 /web/discuss/vendor/flarum/core/src/Extension/ExtensionManager.php(241): Flarum\Database\Migrator->run('/web/discuss/pu...', Object(Flarum\Extension\Extension))↵#6 /web/discuss/vendor/flarum/core/src/Extension/ExtensionManager.php(127): Flarum\Extension\ExtensionManager->migrate(Object(Flarum\Extension\Extension))↵#7 /web/discuss/vendor/flarum/core/src/Api/Controller/UpdateExtensionController.php(49): Flarum\Extension\ExtensionManager->enable('jjandxa-chinese...')↵#8 /web/discuss/vendor/flarum/core/src/Http/RouteHandlerFactory.php(40): Flarum\Api\Controller\UpdateExtensionController->handle(Object(Zend\Diactoros\ServerRequest))↵#9 /web/discuss/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(67): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Zend\Diactoros\ServerRequest), Array)↵#10 /web/discuss/vendor/zendframework/zend-stratigility/src/Next.php(52): Flarum\Http\Middleware\DispatchRoute->process(Object(Zend\Diactoros\ServerRequest), Object(Closure))↵#11`

**Comment by oyjcmyn** [comment]
已经解决

**Comment by alexxd35** [comment]
> 已经解决

你好，请问如何在beta8安装这个插件呢

**Comment by jjandxa** [comment]
packagist 没更新缓存，现在已经 OK了。
