### ISSUE TITLE
大佬请尽快适配beta8.1版本

### ISSUE THREAD

**Issue by AkitoSilver** [jjandxa/flarum-ext-chinese-search#6]

**Comment by jjandxa** [comment]
经测试，可以兼容 beta8.1

**Comment by DoYHang** [comment]
> 经测试，可以兼容 beta8.1

beta8.1安装迅搜以后在搜索框搜索内容会出现Oops! Something went wrong. Please reload the page and try again.是什么问题

**Comment by DoYHang** [comment]
> > 经测试，可以兼容 beta8.1
> 
> beta8.1安装迅搜以后在搜索框搜索内容会出现Oops! Something went wrong. Please reload the page and try again.是什么问题

[XSException] vendor/hightman/xunsearch/lib/XSServer.class.php(307): None of database avaiable(S#506)
#0 vendor/hightman/xunsearch/lib/XSSearch.class.php(645): XSServer->execCommand(Object(XSCommand), 206)
#1 Quest.php(308): XSSearch->search()
#2 xs(26): require('/var/www/html/y...')
#3 {main}

**Comment by book-boy** [comment]
> 经测试，可以兼容beta8.1

不能启用插件！！！8.1
