### ISSUE TITLE
服务器测试搜索结果有，网站前台搜索不能展示

### ISSUE THREAD

**Issue by iosmall** [jjandxa/flarum-ext-chinese-search#7]
// 测试搜索结果
./vendor/bin/xs search -p ./vendor/jjandxa/flarum-ext-chinese-search/app.ini -q 关键词
以上服务器测试能出来数据结果。
网站前台搜索没有结果，8.1的版本启用插件错误

**Comment by jjandxa** [comment]
flarum 版本 0.1.0-beta.8.1
