### ISSUE TITLE
为什么这个沙雕插件会把我几乎所有插件都卸载了？？？？这是什么弱智设计？？？辛辛苦苦跳的插件全没了！！！！！

### ISSUE THREAD

**Issue by ceerker** [jjandxa/flarum-ext-chinese-search#8]
为什么这个沙雕插件会把我几乎所有插件都卸载了？？？？这是什么弱智设计？？？辛辛苦苦跳的插件全没了！！！！！

**Comment by ceerker** [comment]
一人吃饱全家不饿插件？？？？我辛辛苦苦就用你一个插件吗？？？？？

**Comment by ceerker** [comment]
开发者要不以后去写病毒吧，连点赞插件都给我卸载了，现在网站完全打不开，服了

**Comment by jjandxa** [comment]
![CU~G10WD4SWS3V6Z 6%P$OQ](https://user-images.githubusercontent.com/10411770/58063735-fd438800-7bb1-11e9-9108-3f5aa1393420.jpg)

**Comment by sendya** [comment]
自己操作不当

**Comment by mynuolr** [comment]
![middle_350x242-184858_v2_10741545216538647_cf4417333f6ea36055dc3fc4d974d4e3](https://user-images.githubusercontent.com/3831242/58063766-295f0900-7bb2-11e9-8e07-6026d78728a1.gif)

**Comment by Tacono** [comment]
![QQ图片20190521102846](https://user-images.githubusercontent.com/24770476/58064054-4ba55680-7bb3-11e9-8969-c5542485010b.jpg)发现aipc用户

**Comment by ceerker** [comment]
你才是傻狗

Tacono <notifications@github.com> 于2019年5月21日周二 上午10:29写道：
